Add CVar `mapm_extend_map_if_no_votes`
Mistrick/MapManagerModular pull request #27
Opened 2021-09-09 05:10 UTC by Nord1cWarr1or

Add CVar `mapm_extend_map_if_no_votes`, which allows you to extend the current map if no one has voted.

2021-09-09 06:01 UTC, Mistrick commented
Всё должно быть реализовано в планировщике. В ядро лишь добавить недостающий API для реализации.

2021-09-09 06:15 UTC, Mistrick requested changes
Всё должно быть реализовано в планировщике. В ядро лишь добавить недостающий API для реализации.

2021-09-22 06:30 UTC, Nord1cWarr1or commented
@Mistrick done.

2021-10-06 10:49 UTC, talnaim2323 commented
I can not open my own request for some reason.
anyway @Mistrick 

Add cvar mapm_change_type 3
its means after vote ending let the owners choose the time they want map change in minutes
now if you set "0", It replaces a map instantly.

Nomination:
option to search map like

in the chat
nom dust

open menu with all maps containing this name.


categories to /maps
By Name(a-z) , Date Added, Last Played, Size, Most popular

that's all!, if the project still active could be nice if all this be in the votemap.
Good Luck!

2021-12-26 15:11 UTC, JUNESYNGOTOFLEX commented
> > Измени версию планировщика.
> 
> Хотел тебе оставить управление версиями. Ведь в других PR я тоже вносил в планировщик правки.
> 
> > На пустом сервере будет вечное продление одной карты.
> 
> Именно этого я и добивался. 
> 
> > Должно ли быть больше продлений чем указано в кваре `mapm_extended_map_max`?
> 
> Не знаю. Можно добавить ещё один режим квара `mapm_extend_map_if_no_votes`, где будет учитываться значение `mapm_extended_map_max`, и если лимит - менять карту. Что скажешь?
> 

you must use 3rd-party plugins for this. сам же делал что продлевает timelimit при пустом сервере

2021-12-27 11:46 UTC, Nord1cWarr1or commented
@JUNESYNGOTOFLEX ты вообще о чём?

2021-12-27 14:51 UTC, JUNESYNGOTOFLEX commented
> > На пустом сервере будет вечное продление одной карты.
> 
> Именно этого я и добивался. 
> 

https://dev-cs.ru/resources/581/

2021-12-27 15:14 UTC, Nord1cWarr1or commented
@JUNESYNGOTOFLEX 
1. Причем тут сейчас сторонний плагин?
2. Функционал, который я предлагаю в этом реквесте, продлит текущую карту, в отличие от моего плагина, который сменит её на стандартную.

2021-12-27 17:50 UTC, JUNESYNGOTOFLEX commented
> @JUNESYNGOTOFLEX 
> 1. Причем тут сейчас сторонний плагин?
> 2. Функционал, который я предлагаю в этом реквесте, продлит текущую карту, в отличие от моего плагина, который сменит её на стандартную.

Плагин создан для небольших серверов с низким онлайном.

Работает по следующему принципу:

Как только на сервере становится меньше игроков чем задано кваром, меняет текущую карту на заданную и устанавливает mp_timelimit = 0.

Сервера с данным плагином (GameTracker).

2021-12-27 17:55 UTC, JUNESYNGOTOFLEX commented
> @JUNESYNGOTOFLEX 
> 1. Причем тут сейчас сторонний плагин?
> 2. Функционал, который я предлагаю в этом реквесте, продлит текущую карту, в отличие от моего плагина, который сменит её на стандартную.

я не доглядел что он меняет карту кроме как устанавливает timelimit в 0, это почти одно и тоже в лучшем случае как я сказал это написать сторонний плагин на пару строк даже не использовав апи от этой системы.

2022-01-02 11:13 UTC, Nord1cWarr1or commented
@Mistrick я добавил зависимость от `mapm_extend_map_if_no_votes`

2022-01-02 18:48 UTC, Mistrick requested changes
Версию плагину нужно апнуть.

2022-01-02 18:48 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_scheduler.sma
> +    new bool:bNeedExtend = bool:(!total_votes && (extend_map_no_votes && g_iExtendedNum < get_num(EXTENDED_MAX)));
Измени `bNeedExtend` на `can_be_extend`
Внутренняя пара скобок ничего не делает и не особо разграничивает условие.

2022-01-02 19:40 UTC, Nord1cWarr1or commented on cstrike/addons/amxmodx/scripting/map_manager_scheduler.sma
> +    new bool:bNeedExtend = bool:(!total_votes && (extend_map_no_votes && g_iExtendedNum < get_num(EXTENDED_MAX)));
@Mistrick 
Может тогда вообще так: 
```
new bool:can_be_extend = bool:(equali(map, g_sCurMap) || !total_votes && extend_map_no_votes && g_iExtendedNum < get_num(EXTENDED_MAX));

    // map extended
    if(can_be_extend) {
```

2022-01-05 15:31 UTC, merged