Polish translation
Mistrick/MapManagerModular pull request #36
Opened 2022-03-31 23:03 UTC by PawelCode

2022-04-15 00:56 UTC, Mistrick commented
Can anyone check the translation?

2022-04-18 20:24 UTC, Happy2906 commented
As far as I can see, the translation is correct.

2022-04-19 09:16 UTC, Mistrick requested changes

2022-04-19 09:16 UTC, Mistrick commented on cstrike/addons/amxmodx/data/lang/mapmanager.txt
> +MAPM_NOBODY_VOTE = Nikt nie oddal glosu. .
remove second dot

2022-04-19 17:21 UTC, PawelCode commented on cstrike/addons/amxmodx/data/lang/mapmanager.txt
> +MAPM_NOBODY_VOTE = Nikt nie oddal glosu. .
Done

2022-04-21 14:20 UTC, merged