New plugin: online checker
Mistrick/MapManagerModular pull request #38
Opened 2022-09-02 21:14 UTC by wopox1337

TODO: 
 - [ ] add 1.8.2 support

2022-09-03 01:16 UTC, Mistrick requested changes
Вижу отступы в 2 пробела, во всем проекте стоит 4.

2022-09-03 01:16 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  get_mapname(g_CurrentMap[Map], charsmax(g_CurrentMap[Map]));
Нужно сохранить в `plugin_cfg`, есть аддоны со сменой имени карты(2х2).

2022-09-03 01:16 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  for(new i, size = ArraySize(maplist); i < size; i++) {
Для читаемости можно дернуть `mapm_get_map_index` и по индексу сразу получить данные.

2022-09-03 01:16 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  new bool: IsOnlineIncorrect = (current_online < g_CurrentMap[MinPlayers] || current_online > g_CurrentMap[MaxPlayers]);
Выбивается стиль. `is_online_incorrect`

2022-09-03 01:16 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  g_pCvars[CHECK_TIMEOUT] = register_cvar("mapm_online_check_timeout", "120");
Добавить описание кваров в `map_manager.cfg`

2022-09-03 01:16 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  set_fail_state("Map '%s' not found in 'maps.ini'", g_CurrentMap[Map]);
С `adv_lists` может быть любое название файла. Список может загрузиться в течение текущей карты, т.е. этот форвард будет вызван больше одного раза за карту. В первом списке карта может быть, во втором нет и наоборот.

2022-09-03 01:16 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  g_pCvars[CHECK_INTERVAL] = register_cvar("mapm_online_check_interval", "30");
В описание желательно добавить, что значение закэшировано и квар не поддерживание изменение на лету.

2022-09-04 00:02 UTC, Mistrick requested changes

2022-09-04 02:52 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +public mapm_can_be_extended(type) {
Добавить проверку, что тип голосования `VOTE_BY_INCORRECT_ONLINE`?

2022-09-07 09:33 UTC, Mistrick commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +    if(g_CurrentMap[MaxPlayers] == INVALID_MAP_INDEX) {
Выглядит как костыль. Почему не выключить таск, если нет данных о карте? Включить, если был выключен.

2022-09-13 11:50 UTC, merged

2022-09-13 14:53 UTC, wopox1337 commented on cstrike/addons/amxmodx/scripting/map_manager_online_checker.sma
> +  get_mapname(g_CurrentMap[Map], charsmax(g_CurrentMap[Map]));
только, вот проблемка. в форвард `mapm_maplist_loaded()` вызывается раньше `plugin_cfg()`. 
Соответственно, в переменной пустота в момент использования.